// eslint-disable-next-line filenames/match-exported
import { KumaRegistry } from "@kuma-ui/next-plugin/registry";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "ress";
import "./globals.scss";
import "./mq-settings.scss";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Posttie",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="ja">
      <body>
        <KumaRegistry>{children}</KumaRegistry>
      </body>
    </html>
  );
}
